name: PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  should_build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          cache-from: type=gha
          # linux/amd64 supports all x86 CPUs
          # linux/amd64/v2 supports x86 CPUs from 2010+
          # linux/amd64/v3 supports x86 CPUs from 2015+
          # https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels
          platforms: linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/arm64
          pull: true
